### ISSUE TITLE
A question about loss of pairwise learning

### ISSUE THREAD

**Issue by ShiguangSun** [LostXine/elo-sac#1]
Hello，I'm interested in this work. But I find that in els_sac.py, there are only curl loss and DINO loss. However, the paper also shows the results of BYOL and SimSiam. Why are there no implementations of these two losses in the code?

**Comment by LostXine** [comment]
Hi @ShiguangSun ,

Thanks for your interest. This repo is for evolving loss searching. In this setting, only CURL and DINO are in the search space that’s why the current repo does not contain other losses. I will upload the code you requested soon.

Best,

**Comment by LostXine** [comment]
Hi @ShiguangSun , 

The core code for BYOL and SimSiam has been updated at [byol_sac.py](https://github.com/LostXine/elo-sac/blob/main/byol_sac.py) and [simsiam_sac.py](https://github.com/LostXine/elo-sac/blob/main/simsiam_sac.py). 

Best,

**Comment by ShiguangSun** [comment]
Thanks！
